# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171016_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_deleted',
        ),
    ]
