# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_blog_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('createdata', models.DateTimeField(auto_now_add=True)),
                ('changedata', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='timeCreated',
            new_name='createdata',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogname',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Blog'),
        ),
    ]
